name: build

on:
    push:
        branches: ["*"]
    pull_request:
        branches: [main]
    workflow_dispatch:

env:
    CODECOV_TOKEN: ${{secrets.CODECOV_TOKEN}}

permissions:
    contents: read
    pull-requests: read

# This allows a subsequently queued workflow run to interrupt previous runs
concurrency:
    group: "${{ github.workflow }} @ ${{ github.event.pull_request.head.label || github.head_ref || github.ref }}"
    cancel-in-progress: true

jobs:
    build:
        runs-on: ${{matrix.os}}
        if: always()
        strategy:
            matrix:
                include:
                    - os: windows-latest
                      node: 18.20.3
                      allowed-to-fail: false
                    - os: windows-latest
                      node: 20.15.0
                      allowed-to-fail: true
        continue-on-error: ${{matrix.allowed-to-fail}}

        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Install Node.js ${{matrix.node}}
              uses: actions/setup-node@v4
              with:
                  node-version: ${{matrix.node}}

            - uses: pnpm/action-setup@v4
              name: Install pnpm
              with:
                  version: 9
                  run_install: false

            - name: Get pnpm store directory
              shell: bash
              run: |
                  echo "STORE_PATH=$(pnpm store path --silent)" >> $GITHUB_ENV

            - uses: actions/cache@v4
              name: Setup pnpm cache
              with:
                  path: ${{ env.STORE_PATH }}
                  key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
                  restore-keys: |
                      ${{ runner.os }}-pnpm-store-

            - name: Install dependencies
              run: pnpm i -frozen-lockfile

            - name: Run test
              run: pnpm run test
